/**
 * AI assistant — calls the real backend /api/ai/analyze endpoint.
 * Answers are grounded in confirmed Supabase data + educational RAG,
 * generated by Azure GPT via the backend's safety-constrained prompt.
 */

export interface AssistantBar {
  label: string;
  percent: number;
}

export interface AssistantMessage {
  role: "user" | "assistant";
  text: string;
  bars?: AssistantBar[];
  /** Data-period badge text. */
  period?: string;
  /** Cautionary/limitation note. */
  note?: string;
  /** Loading indicator. */
  loading?: boolean;
}

export const suggestedQuestions = [
  "Which drinks contributed most to my sugar?",
  "How did this week compare with last week?",
  "What is HbA1c?",
  "Which entries were estimates?",
];

export function greetingMessage(): AssistantMessage {
  return {
    role: "assistant",
    text: "Hi! Ask me anything about your nutrition — I answer from your confirmed logs and approved health knowledge. I don't diagnose or prescribe.",
  };
}

export function loadingMessage(): AssistantMessage {
  return {
    role: "assistant",
    text: "Thinking…",
    loading: true,
  };
}

interface BackendAnalyzeResponse {
  answer: string;
  period_start?: string;
  period_end?: string;
  medical_disclaimer?: string | null;
  incomplete_logging?: boolean;
  sources?: { kind: string; label: string; detail?: string }[];
}

/**
 * Call the real backend AI analyzer. Returns a formatted AssistantMessage.
 * Falls back to an error message if the backend is unreachable.
 */
export async function askBackend(question: string): Promise<AssistantMessage> {
  try {
    const res = await fetch("/api/ai/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ question, user_id: "default" }),
    });

    if (!res.ok) {
      const body = await res.json().catch(() => null);
      const detail = body?.detail || res.statusText;
      return {
        role: "assistant",
        text: `Sorry, I couldn't get an answer right now. (${detail})`,
      };
    }

    const data: BackendAnalyzeResponse = await res.json();

    const period =
      data.period_start && data.period_end
        ? `${formatShortDate(data.period_start)} – ${formatShortDate(data.period_end)}`
        : undefined;

    const note = data.medical_disclaimer
      ? data.medical_disclaimer
      : data.incomplete_logging
        ? "Some days have incomplete logging, so totals may be underestimated."
        : undefined;

    return {
      role: "assistant",
      text: data.answer,
      period,
      note,
    };
  } catch {
    return {
      role: "assistant",
      text: "Couldn't reach the backend. Make sure the server is running on port 8000.",
    };
  }
}

function formatShortDate(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  } catch {
    return iso;
  }
}
